name: 'Create Discussion Comment'
description: 'Create Comments on Exsiting GitHub Discussions using GitHub Actions'
author: 'Wesley Scholl'
branding:
  icon: message-square
  color: green
runs:
  using: 'docker'
  image: 'Dockerfile'
  
