#!/bin/bash

# Demo script for create-discussion-comment - GitHub Discussions automation

set -e

echo "=========================================="
echo "  💬 Create Discussion Comment Action"
echo "  GitHub Discussions Automation Tool"
echo "=========================================="
echo ""

echo "🔍 Action Overview:"
if [ -f "action.yml" ]; then
    echo "   ✅ GitHub Action configured"
    echo "   Purpose: Automated discussion comment creation"
    echo "   Type: Composite action"
else
    echo "   ⚠️  action.yml not found"
fi

echo ""
echo "✨ Key Features:"
echo ""
echo "   💬 Comment Management"
echo "      • Create discussion comments via API"
echo "      • Support for markdown formatting"
echo "      • Thread-safe operations"
echo "      • Rate limiting handling"
echo ""
echo "   🔧 Automation Capabilities"
echo "      • Triggered by workflow events"
echo "      • Conditional comment posting"
echo "      • Template support"
echo "      • Variable interpolation"
echo ""
echo "   🎯 Use Cases"
echo "      • Automated release notes"
echo "      • Bot responses to discussions"
echo "      • Status updates"
echo "      • Community engagement"
echo ""

echo "📝 Usage Example:"
echo ""
echo "   name: Post Discussion Comment"
echo "   on:"
echo "     discussion:"
echo "       types: [created]"
echo ""
echo "   jobs:"
echo "     comment:"
echo "       runs-on: ubuntu-latest"
echo "       steps:"
echo "         - uses: wesleyscholl/create-discussion-comment@v1"
echo "           with:"
echo "             token: \${{ secrets.GITHUB_TOKEN }}"
echo "             discussion-id: \${{ github.event.discussion.number }}"
echo "             body: |"
echo "               Thanks for starting this discussion!"
echo "               We'll review it shortly."
echo ""

echo "🚀 Quick Start:"
echo ""
echo "   1. Add to your workflow:"
echo "      .github/workflows/discussion-bot.yml"
echo ""
echo "   2. Configure inputs:"
echo "      • token: GitHub token"
echo "      • discussion-id: Discussion number"
echo "      • body: Comment text (markdown supported)"
echo ""
echo "   3. Deploy:"
echo "      git push → workflow runs automatically"
echo ""

echo "💡 Advanced Features:"
echo "   • Markdown rendering"
echo "   • @mentions support"
echo "   • Emoji reactions ❤️ 🎉 👀"
echo "   • File attachments"
echo "   • Comment editing/deletion"
echo ""

echo "📊 Benefits:"
echo "   • Automate community engagement"
echo "   • Consistent messaging"
echo "   • Reduce manual work"
echo "   • Improve response times"
echo "   • Scale discussion management"
echo ""

echo "=========================================="
echo "  Repository: github.com/wesleyscholl/create-discussion-comment"
echo "  Type: GitHub Action | Status: Production-Ready"
echo "=========================================="
echo ""
