name: Create Comment
on: [workflow_dispatch]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Run create-discussion-comment
      uses: wesleyscholl/create-discussion-comment@v1.0.10
      id: create-comment
      with:
        discussion-id: 'D_kwDOKEe7W84AVXOO'
        client-mutation-id: '8888'
        body: "This is a test comment from a GitHub action"
        token: ${{ secrets.DISCUSS_TOKEN }}

    - name: echo output from create-discussion-comment
      run: |
        echo ${{ steps.create-comment.outputs.commentid }}